---
- name: Let's Clone the ubigate repository.
  git: repo=git@github.com:pawmint/ubiGATE.git dest=/home/{{ user }}/ubigate version=stable_2016_03 depth=1 accept_hostkey=true  
  sudo: yes

- name: Install ubigate.
  command: python setup.py install chdir="/home/{{ user }}/ubigate"

- name: Install marmitek plugin.
  command: ubigate-plugin-manager install https://github.com/pawmint/marmitek-gw/ --branch=dev

- name: Copy ubigate systemd service
  template: src=ubigate.service dest=/lib/systemd/system/

- name: enable ubigate systemd service
  command: sudo systemctl {{ item }} ubigate.service
  with_items:
    - enable
    - start

#- name: adding entry to cron.d
 # template: src=etc_cron.d_ubigate_update.j2 dest=/etc/cron.d/ubigate-update owner=root group=root mode=0644
