#!/bin/bash
#ask if there is a raspberry set up wanna use it or not
#if yes read the path to the file
#if not clone and set the path value to the cloned repository
#'cloning raspberry setup'
#sudo git clone https://github.com/pawmint/raspberry_setup.git
# after cloning it  we simply  run it
# remove the set points
##############################################################################################################
h1 'Raspbian installation'

until [ "$INSTALL" = "y" -o "$INSTALL" = "n" ]; do
	read -r -p "Is raspbian already installed on your SD card? (y/n)" INSTALL
	INSTALL=`echo "$INSTALL" | tr '[:upper:]' '[:lower:]'`
done
#Setting up the SD card
if [ "$INSTALL" = "n" ]; then
#	PAT='' #path to the raspberry setup script
#	until [ "$VAR" = "y" -o "$VAR" = "n" ]; do
#		read -r -p "Do want to clone the raspberry setup script? (Y/n) " VAR
#		VAR=`echo "$VAR" | tr '[:upper:]' '[:lower:]'`
#	done
#	if [ "$VAR" = "y" ]; then
#		git clone  https://github.com/pawmint/raspberry_setup.git
#	else
#		ok=1
#		until [ $ok = 0 ]; do
#			read -r -p "Type the absolute path to the directory containing hte raspberrysetup repository(not the one containing the script)" PAT
#			PAT=`echo "$PAT" | tr '[:upper:]' '[:lower:]'`
#			echo $PAT
#			ok=0	
#		done
#	fi
	./firmwareUpdate.sh
fi
#add mount command in firmwareUpdate script
###########################################################################################################
h1 'Ansible Script'
until [ "$SD" = "y" ]; do
        read -r -p "Is your SD card mounted? (y/n)" SD
        SD=`echo "$SD" | tr '[:upper:]' '[:lower:]'`
done
#locating the sd card
media=$(df | awk '/media/ {print $6}')
#extracting the sd card's name
media=`echo "$media" | grep -e '[0-9]' | tr -s ' ' | cut -d ' ' -f 2`
#wifi configuration for model 3 raspberry pi
media="$media/etc/wpa_supplicant/wpa_supplicant.conf"
read -r -p "Type your network ESSID:" ESSID
ESSID=`echo "$ESSID" | tr '[:upper:]' '[:lower:]'`
read -r -p "Type your wifi password:" pass
pass=`echo "$pass" | tr '[:upper:]' '[:lower:]'`

echo "network={

    ssid=”$ESSID”

    psk=”$pass”

    }" >> $media
#running nmap before asking to power on the pi
rm nmap*
nmap -sP 192.168.0.0/24 | grep ".192*" >  nmap1.tmp
#Either connect it with an ethernet cable or use wifi not both at the same time
#By running nmap twice, I am trying to identify the newly added Ip address
read -r -p 'Power on your raspberry pi then Press [Enter] key.' VAR
sleep 30

nmap -sP 192.168.0.0/24 | grep ".192*" >  nmap2.tmp

IPADDRESS=`diff nmap1.tmp nmap2.tmp`
IPADDRESS=`echo ${IPADDRESS:27}`
#echo IPADDRESS=$IPADDRESS
    if [ -z "$IPADDRESS" ]; then
        echo "Can't find your card."
    else
	echo ip=$IPADDRESS
     fi

#adding the ip address to the hosts file
sed -i "s/192.168.0.*/${IPADDRESS}/g" hosts

#install ansible and run the necessarry steps
apt-get install ansible
pip install paramiko --upgrade
ansible-playbook -vvv setup.yml -i hosts --ask-pass --sudo -c paramiko
