---

- name: Ansible Playbook for configuring brand new Raspberry Pi

  hosts: raspberries
  roles:
    - common
    - expand-rootfs
    - oh-my-zsh
    - mochad
    - ubigate
  remote_user: pi
  sudo: yes
