---

- hosts: all
 
  tasks:

   - name: Install ubigate.
     command: python setup.py install chdir="/home/pi/ubigate"

   - name: Install marmitek plugin.
     command: ubigate-plugin-manager install https://github.com/pawmint/marmitek-gw/ --branch=dev

   - name: Copy ubigate systemd service
     copy: src=ubigate.service dest=/lib/systemd/system/

   - name: enable ubigate systemd service
     command: sudo systemctl {{ item }} ubigate.service
     with_items:
      - enable
      - start
